# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FranklinBarbershop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FranklinBarbershop
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'FranklinBarbershopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FranklinBarbershopUITests' do
    # Pods for testing
  end

end
